### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by IMrLawrence** [IMrLawrence/odin-recipes#1]
Initial Structure:
 - [x] Create `index.html`;
 - [x] Add an Title on body;

Recipe Page:
 - [x] Create a dir for recipes;
 - [x] Create a recipe HTML file;
 - [x] Add a title for the page;
 - [x] Create link on `index.html` for your recipe webpage;

Recipe Page Content:
 - [x] Add a image of the finished dish under title;
 - [x] Create a description for the recipe;
 - [x] Show the ingredients;
 - [x] Show the Step-by-Step of the recipe;

Add More Recipes:
 - [x] Add two more recipes with identical page structure of the first recipe;
 - [x] Add links for the recipes on the `index.html`;
